### ISSUE TITLE
Problem with acrcloud_extr_tool.so

### ISSUE THREAD

**Issue by daxeel** [acrcloud-demo/audio-recognition-quick-trial#1]
I just followed tutorial given in readme and getting this error. Help me how to solve.

Traceback (most recent call last):
  File "test.py", line 9, in <module>
    from acrcloud.recognizer import ACRCloudRecognizer
  File "/Users/daxeelsoni/Desktop/DeftellAI/code/DeftellAI-venv/scripts/acr/acrcloud/recognizer.py", line 20, in <module>
    import acrcloud_extr_tool.so
ImportError: dlopen(/Users/daxeelsoni/Desktop/DeftellAI/code/DeftellAI-venv/scripts/acr/acrcloud/acrcloud_extr_tool.so, 2): no suitable image found.  Did find:
	/Users/daxeelsoni/Desktop/DeftellAI/code/DeftellAI-venv/scripts/acr/acrcloud/acrcloud_extr_tool.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00

**Comment by acrcloud-demo** [comment]
Hi Daxeel，
    Did you use Macbook? Unfortunately, acrcloud_extr_tool.so is compiled in Linux Environment as mentioned in README, it doesn't support MacOS now and it will in the future.

**Comment by daxeel** [comment]
Ok @acrcloud-demo . Thanks for your reply.
